stages:
  - check

nix-check:
  stage: check
  image: nixos/nix:latest
  script:
    - nix --extra-experimental-features "nix-command flakes" flake check
    - nix --extra-experimental-features "nix-command flakes" run nixpkgs#statix -- check
  only:
    - main
    - merge_requests
