stages:
  - check

nix-check:
  stage: check
  image: nixos/nix:latest
  variables:
    NIX_CONFIG: "extra-experimental-features = nix-command flakes"
  script:
    - echo "Checking Nix syntax & Flake evaluation..."
    - nix flake check
    - echo "Running Statix linter..."
    - nix run nixpkgs#statix -- check
  only:
    - main
    - merge_requests
