# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6c5bee7c-4d3b-4cce-b8ef-7be8fed1bc56";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6c5bee7c-4d3b-4cce-b8ef-7be8fed1bc56".device = "/dev/disk/by-uuid/6c5bee7c-4d3b-4cce-b8ef-7be8fed1bc56";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9DB7-A212";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
